name: Unit tests
on: [push]
jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.5

      - name: Install modules
        run: CYPRESS_INSTALL_BINARY=0 npm install

      - name: Run tests
        run: npm test
